### ISSUE TITLE
[conan-center] export/conandata.yml gets modified by hooks

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/hooks#151]
Hello,

I'm using a `conandata.yml` in my recipe, copied from CCI:

```yaml
sources:
  "2.9.2":
    url: "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.9.2.tar.gz"
    sha256: "c4c78167fae325b47aebd8beb54b6041d6f6a56b3743f4bd5d79b15642f9d5d4"
```
After running a `conan create`, here is what gets written in the `export/conandata.yml` file:

```yaml
sources:
  2.9.2:
    sha256: c4c78167fae325b47aebd8beb54b6041d6f6a56b3743f4bd5d79b15642f9d5d4
    url: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.9.2.tar.gz
```

As you can see, quotes have been removed, and fields reordered alphabetically.
This is undesired, especially when using lockfiles, since it creates a new recipe revision.
