### ISSUE TITLE
[conan-center-index] Accept mirrors in conandata.yml

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#168]
Hi!

The KB-H031 (Conan data reduce), filters package version which contains suffixes (e.g 1.0.0-mirror), resulting in a fail. It would be nice having a specific key only for mirrors:

```yaml
sources:
  "1.2.11":
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: https://zlib.net/zlib-1.2.11.tar.gz
mirrors:
  "1.2.11":
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz
```

Related issue: https://github.com/conan-io/conan-center-index/issues/1095

Regards!
