### ISSUE TITLE
[bug] exported conandata.yml end up an empty dict

### ISSUE THREAD

**Issue by braindevices** [conan-io/hooks#201]
when I add custom data in conandata.yml.
```
system-packages:
  ubuntu:
    libunwind: libunwind-dev
    glib-2.0: libglib2.0-dev
  fedora:
    libunwind: libunwind-devel
    glib-2.0: glib-devel
  osx:
    libunwind: null
    glib-2.0: null
  fallback:
    libunwind: libunwind/1.3.1
    glib-2.0: glib/2.64.0
```
`conan export` works fine on ubuntu and fedora, but on osx, in the export folder, the conandata.yml end up this:
```
{}
```
### Environment Details (include every applicable attribute)
  * Operating System+version: 10.15.4
  * Compiler+version: N/A
  * Conan version: 1.25.2
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
create a conan package with conandata.yml containing some custom data fields. Then export. Check the conandata.yml in export folder.
