### ISSUE TITLE
[conan-centre] conandata.yml different sources per configuration

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#259]
from https://github.com/conan-io/conan-center-index/pull/3004

right now, `conandata.yml` is very restrictive.

there are several use-cases we may need to satisfy:

1. simple case, just a single source (per version)
example: https://github.com/conan-io/conan-center-index/blob/master/recipes/asio/all/conandata.yml
```

sources:
  "1.18.0":
    sha256: 820688d1e0387ff55194ae20036cbae0fb3c7d11b7c3f46492369723c01df96f
    url: https://github.com/chriskohlhoff/asio/archive/asio-1-18-0.tar.gz
```

2. single source with download mirror(s)
example: https://github.com/conan-io/conan-center-index/blob/master/recipes/zlib/1.2.11/conandata.yml
```
sources:
  "1.2.11":
    url: [
         "https://zlib.net/zlib-1.2.11.tar.gz",
         "https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz",
       ]
    sha256: "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1"
```
now, URL is an array

3. source code and license on its own URL
example: https://github.com/conan-io/conan-center-index/blob/master/recipes/approvaltests.cpp/all/conandata.yml
```
sources:
  8.0.0:
    - url: https://github.com/approvals/ApprovalTests.cpp/releases/download/v.8.0.0/ApprovalTests.v.8.0.0.hpp
      sha256: e16a97081f8582be951d95a9d53dc611f1f5a84e117a477029890d0b34ae99d6
    - url: "https://raw.githubusercontent.com/approvals/ApprovalTests.cpp/v.8.0.0/LICENSE"
      sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4
```
now we have multiple URL and sha256 entries

4. several source code archives. technically, same use case as 3
example: https://github.com/conan-io/conan-center-index/blob/master/recipes/opencv/4.x/conandata.yml
```
sources:
  "4.5.0":
    - sha256: dde4bf8d6639a5d3fe34d5515eab4a15669ded609a1d622350c7ff20dace1907
      url: https://github.com/opencv/opencv/archive/4.5.0.tar.gz
    - sha256: a65f1f0b98b2c720abbf122c502044d11f427a43212d85d8d2402d7a6339edda
      url: https://github.com/opencv/opencv_contrib/archive/4.5.0.tar.gz
```

5. different source code archives per configuration (e.g. per architecture), index-based
example: https://github.com/conan-io/conan-center-index/blob/master/recipes/msys2/all/conandata.yml
```
sources:
  "20161025":
    - url: [
             "http://repo.msys2.org/distrib/i686/msys2-base-i686-20161025.tar.xz",
             "https://sourceforge.net/projects/msys2/files/Base/i686/msys2-base-i686-20161025.tar.xz",
      ]
      sha256: "8bafd3d52f5a51528a8671c1cae5591b36086d6ea5b1e76e17e390965cf6768f"
    - url: [
             "http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20161025.tar.xz",
             "https://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20161025.tar.xz"
    ]
      sha256: "bb1f1a0b35b3d96bf9c15092da8ce969a84a134f7b08811292fbc9d84d48c65d"
```
the structure is the same as case 3 - multiple URL entries. the recipe uses an index to access the required source code archive.

6. different source code per configuration, name based
example: https://github.com/conan-io/conan-center-index/blob/master/recipes/cspice/all/conandata.yml
```
sources:
  "0066":
    url:
      "Macos":
        "apple-clang":
          "x86": "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_32bit/packages/cspice.tar.Z"
          "x86_64": "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z"
```
seems like it doesn't follow our format - e.g. it doesn't have URL or sha256 fields at all

proposal:
I guess, ultimately we want something like name-based approach 6, with an arbitrary level of nesting, having URL and sha256 fields. it may look like:
```
sources:
  "0066":
    url:
      "Macos":
        "apple-clang":
          "x86":
            - url: "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_32bit/packages/cspice.tar.Z"
              sha256: "xxx"
          "x86_64":
            - url: "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z"
              sha256: "xxx"
```
we also want to support (optional) mirroring, so URL might be an array here (just like in case 2):
```
sources:
  "0066":
    url:
      "Macos":
        "apple-clang":
          "x86":
            - url: [
            "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_32bit/packages/cspice.tar.Z",
            "https://mirror.naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_32bit/packages/cspice.tar.Z"
            ]
              sha256: "xxx"
```

what to do?

- [x] agree on the more flexible `conandata.yml` format
- [ ] update conan-center hooks to allow format agreed
- [ ] deploy conan-center hooks on CCI
- [ ] update recipes (probably, msys2, cspice and android-ndk) to follow the new format

**Comment by SpaceIm** [comment]
Seems that the first url key is useless.

Would it be allowed to remove this first url key?

```yml
sources:
  "0066":
    "Macos":
      "apple-clang":
        "x86":
          - url: "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_32bit/packages/cspice.tar.Z"
            sha256: "xxx"
        "x86_64":
          - url: "https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z"
            sha256: "xxx"
```
