### ISSUE TITLE
[conan centre] conandata.yml extended format for patches

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#268]
the current format is:
```
  1.75.0:
    - patch_file: "patches/boost_build_qcc_fix_debug_build_parameter_since_1_74.patch"
      base_path: "source_subfolder"
    - patch_file: "patches/python_base_prefix_since_1_74.patch"
      base_path: "source_subfolder"
```
we want more fields according to the discussion at https://github.com/conan-io/conan-center-index/pull/3951

the proposal format would be:
```
  1.75.0:
    - patch_file: "patches/boost_build_qcc_fix_debug_build_parameter_since_1_74.patch"
      base_path: "source_subfolder"
      patch_type: <the type of the patch>
      patch_description: <short description on what does patch do, why does it do that and how>
      patch_source: <the original location patch was taken from>
```

there are several new (mandatory) fields: `patch_type`, `patch_description` and `patch_source`.
let's discuss them in details:

1. patch_type

there are several patch types we want to allow in conan centre right away.

1.1. official

`patch_type: official` indicates the patch is distributed with source code itself. usually, this happens if release managers failed to include a critical fix to the release, but it's too much burden to make new release just because of that one fix.
example: https://www.boost.org/users/history/version_1_72_0.html (notice the `coroutine patch`)

in that case, the description could be copied from the release page, and the release page would be the patch source itself

1.2. vulnerability

the patch addresses the security issue. the patch description should include the index of CVE or CWE the patch addresses.
usually, upstream does new releases for vulnerabilities itself, but some projects are abandoned or inactive.

1.3. backport

the patch backports existing bug fix from the newer release or master branch (or equivalent, such as main/develop/trunk/etc). the patch address may be a pull request, or bug issue tracker entry.

1.4. portability

the patch improves the portability of the library, e.g. adding supports of new architectures (ARM, Sparc, etc.), operation systems (FreeBSD, Android, etc.), compilers (Intel, MinGW, etc.), and other types of configurations.

in such cases, patch could be adopted from another package repository (e.g. MSYS packages, Debian packages, Homebrew, FreeBSD ports, etc.).

2. patch_source

`patch_source` is an URL from where patch was taken from, https is preferred, but other URLs (e.g. git/svn/hg) are also accepted if there is no alternative. what could be a patch source?

- link to the public commit in project hosting like GitHub/GitLab/BitBucket/Savanha/SourceForge/etc
- link to the Pull Request 
- link to the bug tracker (such as JIRA, BugZilla, etc.)
- link to the mail list discussion
- link to the patch itself in another repository (e.g. MSYS, Debian, etc.)

3. patch_description

`patch_description` is an arbitrary text describing the following aspects of the patch:
- what does patch do (example - `add missing unistd.h header`)
- why is it necessary (example `port to Android`)
- how exactly does patch (example - `update configure.ac`)
therefore, the full description may look like: `port to android: update configure.ac adding missing unistd.h header`
